--- 
build: 
  build_steps: 
    - "apt update"
    - "apt install -y libglib2.0-0 libsm6 libxext6 libxrender-dev git"
    - "pip install -r requirements.txt"
  image: "pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime"
environment: 
  node_selector: 
    nvidiaDriver: "450"
  resources: 
    cpu: 
      limits: 4
      requests: 3
    gpu: 
      limits: 1
      requests: 1
    memory: 
      limits: 32000
      requests: 20000
framework: pytorch
kind: experiment
params: 
  CUT_mode: CUT
  batch_size: 1
  dataroot: /Prostate_Reg_KM/Anonymized_cleaned/
  dataset_mode: volume
  display_freq: 50
  display_id: -1
  epoch: latest
  epoch_count: 0
  epochs_before_reg: 10
  input_nc: 1
  load_init_models: /data/Prostate_Reg_KM/multitask/init_weights_cut_full_epoch_50/
  load_mask: true
  lr: 0.0002
  lr_Def: 0.0001
  lr_Reg: 0.0001
  lr_Seg: 0.0001
  lr_decay_iters: 1
  lr_policy: step
  model: cut3d_multitask
  n_epochs: 50
  n_epochs_decay: 25
  name: cut3d
  netG: resnet_cat
  netReg: NormalNet
  netSeg: unet_small
  ngf: 24
  output_nc: 1
  print_freq: 20

run: 
  cmd: "GEOMSTATS_BACKEND=pytorch python train.py --batch_size={{ batch_size }}\\ 
	--dataroot={{ dataroot }} \\ 
	--dataset_mode={{ dataset_mode }} \\ 
	--output_nc={{ output_nc }} \\ 
	--input_nc={{ input_nc }} \\ 
	--lr {{ lr }} \\ 
	--lr_Def {{ lr_Def }} \\ 
	--lr_Seg {{ lr_Seg }} \\ 
	--lr_Reg {{ lr_Reg }} \\ 
	--lr_policy={{ lr_policy }} \\ 
	--display_freq={{ display_freq }} \\ 
	--print_freq {{ print_freq }} 
	--lr_decay_iters {{ lr_decay_iters }} \\ 
	--epoch_count={{ epoch_count }} \\ 
	--n_epochs={{ n_epochs }} \\ 
	--n_epochs_decay {{ n_epochs_decay }} \\ 
	--netG={{ netG }} \\ 
	--CUT_mode={{ CUT_mode }} \\ 
	--model={{ model }} \\ 
	--load_mask={{ load_mask }} \\ 
	--epochs_before_reg={{ epochs_before_reg }} \\ 
	--epoch={{ epoch }} \\ 
	--display_id={{ display_id }} \\ 
	--load_init_models={{load_init_models}} \\ 
	--ngf={{ ngf }} \\ 
	--continue_train \\ 
	--netReg={{ netReg }} \\ 
	--netSeg={{ netSeg }} \\ 
	--use_rigid_branch\\
	--reg_idt_B"


tags: 
  - Mutltitask
  - HPTuning
version: 1
