---
version: 1

kind: experiment

framework: pytorch


tags:
  - DeformableRegistration
  - Monomodal

build:
  build_steps:
    - "apt update"
    - "apt install -y libglib2.0-0 libsm6 libxext6 libxrender-dev git"
    - "pip install -r requirements.txt"
  image: "pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime"

environment:
  node_selector:
    gpuMemory: "12"
  resources:
    cpu:
      limits: 4
      requests: 3
    gpu:
      limits: 1
      requests: 1
    memory:
      limits: 16000
      requests: 10000


params:
  dataroot: /Prostate_Reg_KM/Anonymized_cleaned/
  display_freq: 50
  display_id: -1
  epoch: latest
  epoch_count: 0
  epochs_before_reg: 0
  input_nc: 1
  load_mask: true
  lr: 0.0002
  lr_decay_iters: 1
  lr_policy: linear
  model: def_reg
  n_epochs: 50
  n_epochs_decay: 25
  name: DefReg
  output_nc: 1
  print_freq: 20
  load_init_models: /data/Prostate_Reg_KM/multitask/def_reg_test/
  epoch: latest

run:
  cmd: GEOMSTATS_BACKEND=pytorch python train.py \\
    --dataroot={{ dataroot }} \\
    --output_nc={{ output_nc }} \\
    --input_nc={{ input_nc }} \\
    --lr {{ lr }} \\
    --lr_policy={{ lr_policy }} \\
    --display_freq={{ display_freq }} \\
    --print_freq {{ print_freq }}
    --lr_decay_iters {{ lr_decay_iters }} \\
    --epoch_count={{ epoch_count }} \\
    --n_epochs={{ n_epochs }} \\
    --n_epochs_decay {{ n_epochs_decay }} \\
    --model={{ model }} \\
    --load_mask={{ load_mask }} \\
    --epochs_before_reg={{ epochs_before_reg }} \\
    --epoch={{ epoch }} \\
    --display_id={{ display_id }} \\
    --bidir \\
    --inshape 80 80 80 \\
    --similarity NCC \\
    --evalutate_freq 10 \\
    --load_init_models {{ load_init_models }} \\
    --epoch {{ epoch }}