--- 
build: 
  build_steps: 
    - "apt update"
    - "apt install -y libglib2.0-0 libsm6 libxext6 libxrender-dev git"
    - "pip install -r requirements.txt"
  image: "pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime"
environment: 
  node_selector: 
    nvidiaDriver: "450"
  resources: 
    cpu: 
      limits: 4
      requests: 3
    gpu: 
      limits: 1
      requests: 1
    memory: 
      limits: 32000
      requests: 20000
framework: pytorch
kind: experiment
params: 
  batch_size: 1
  dataroot: /Prostate_Reg_KM/Anonymized_cleaned/
  dataset_mode: volume
  display_freq: 50
  display_id: -1
  epoch: latest
  epoch_count: 0
  input_nc: 1
  load_mask: true
  lr: 0.0002
  lr_policy: step
  model: cycle_gan3d
  n_epochs: 200
  n_epochs_decay: 25
  name: cut3d
  netG: resnet_6blocks
  netD: basic
  output_nc: 1
  print_freq: 20
  gan_mode: lsgan

run: 
  cmd: "GEOMSTATS_BACKEND=pytorch python train.py --batch_size={{ batch_size }}\\ 
	--dataroot={{ dataroot }} \\ 
	--dataset_mode={{ dataset_mode }} \\ 
	--output_nc={{ output_nc }} \\ 
	--input_nc={{ input_nc }} \\ 
	--lr {{ lr }} \\ 
	--lr_policy={{ lr_policy }} \\ 
	--display_freq={{ display_freq }} \\ 
	--print_freq {{ print_freq }} 
	--epoch_count={{ epoch_count }} \\ 
	--n_epochs={{ n_epochs }} \\ 
	--netG={{ netG }} \\ 
	--netD={{netD}} \\
    --gan_mode={{gan_mode}}\\
	--model={{ model }} \\ 
	--display_id={{ display_id }} \\ "


tags: 
  - pix2pix3d
version: 1



